-- Foundation for event/private booking requests.
-- These orders are manager-reviewed requests, not automatic confirmations.

CREATE TABLE IF NOT EXISTS event_booking_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    telegram_user_id BIGINT,
    user_id BIGINT,
    venue_code VARCHAR(64) NOT NULL DEFAULT 'AERIS',
    status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
    source VARCHAR(40) NOT NULL DEFAULT 'TELEGRAM',
    event_type VARCHAR(80),
    requested_date DATE,
    requested_time_text VARCHAR(80),
    guest_count INTEGER,
    budget_text VARCHAR(160),
    menu_preferences TEXT,
    technical_requirements TEXT,
    contact TEXT,
    guest_name VARCHAR(160),
    guest_phone VARCHAR(80),
    guest_comment TEXT,
    manager_telegram_id BIGINT NOT NULL DEFAULT 876857557,
    manager_user_id BIGINT,
    manager_chat_id VARCHAR(120),
    external_id VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_event_booking_guest_count CHECK (guest_count IS NULL OR guest_count > 0),
    CONSTRAINT fk_event_booking_orders_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_event_booking_orders_manager_user
        FOREIGN KEY (manager_user_id) REFERENCES users(id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_event_booking_orders_chat_created
    ON event_booking_orders(chat_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_event_booking_orders_status_date
    ON event_booking_orders(status, requested_date, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_event_booking_orders_venue_status
    ON event_booking_orders(venue_code, status, created_at DESC);
