-- Foundation for Hidden Heart / social contribution orders.
-- Payment is direct SBP handoff to an initiative or venue-managed account.

CREATE TABLE IF NOT EXISTS donation_initiatives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_code VARCHAR(64) NOT NULL DEFAULT 'AERIS',
    initiative_code VARCHAR(120) NOT NULL,
    title VARCHAR(240) NOT NULL,
    description TEXT,
    sbp_link TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_donation_initiatives_code UNIQUE (venue_code, initiative_code)
);

CREATE INDEX IF NOT EXISTS idx_donation_initiatives_venue_active
    ON donation_initiatives(venue_code, active, title);

CREATE TABLE IF NOT EXISTS donation_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    telegram_user_id BIGINT,
    user_id BIGINT,
    venue_code VARCHAR(64) NOT NULL DEFAULT 'AERIS',
    initiative_id BIGINT REFERENCES donation_initiatives(id) ON DELETE SET NULL,
    initiative_title VARCHAR(240),
    status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
    source VARCHAR(40) NOT NULL DEFAULT 'TELEGRAM',
    amount_minor BIGINT,
    currency VARCHAR(8) NOT NULL DEFAULT 'RUB',
    anonymous BOOLEAN NOT NULL DEFAULT TRUE,
    guest_name VARCHAR(160),
    guest_comment TEXT,
    sbp_url TEXT,
    payment_external_id VARCHAR(160),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_donation_orders_amount CHECK (amount_minor IS NULL OR amount_minor > 0)
);

CREATE INDEX IF NOT EXISTS idx_donation_orders_chat_created
    ON donation_orders(chat_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_donation_orders_status_created
    ON donation_orders(status, created_at DESC);

INSERT INTO donation_initiatives (
    venue_code,
    initiative_code,
    title,
    description,
    metadata_json
) VALUES
    ('AERIS', 'AERIS_HIDDEN_HEART_DEFAULT', 'Hidden Heart / общий фонд', 'Временная инициатива по умолчанию до загрузки реальных документов и списка инициатив.', '{"default":true}'::jsonb)
ON CONFLICT (venue_code, initiative_code) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    active = TRUE,
    metadata_json = EXCLUDED.metadata_json,
    updated_at = CURRENT_TIMESTAMP;
