-- Smart Solution operational CRM foundation.
-- Telegram remains the fast UI; these tables are the structured source of truth.

CREATE TABLE IF NOT EXISTS ops_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    name VARCHAR(240) NOT NULL,
    vertical VARCHAR(60) NOT NULL DEFAULT 'OTHER',
    stage VARCHAR(60) NOT NULL DEFAULT 'INTAKE',
    status VARCHAR(60) NOT NULL DEFAULT 'ACTIVE',
    owner_name VARCHAR(160),
    team_chat_id VARCHAR(80),
    progress_percent INTEGER NOT NULL DEFAULT 0 CHECK (progress_percent >= 0 AND progress_percent <= 100),
    deadline_at TIMESTAMPTZ,
    next_call_at TIMESTAMPTZ,
    launch_status TEXT,
    result_definition TEXT,
    description TEXT,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ops_projects_status_updated
    ON ops_projects(status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_ops_projects_vertical_updated
    ON ops_projects(vertical, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_ops_projects_deadline
    ON ops_projects(deadline_at);

CREATE TABLE IF NOT EXISTS ops_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES ops_projects(id) ON DELETE CASCADE,
    title VARCHAR(240) NOT NULL,
    owner_name VARCHAR(160),
    status VARCHAR(60) NOT NULL DEFAULT 'TODO',
    priority VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    pipeline_stage VARCHAR(60) NOT NULL DEFAULT 'PLANNING',
    due_at TIMESTAMPTZ,
    deliverable_url TEXT,
    notes TEXT,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ops_tasks_project_status_due
    ON ops_tasks(project_id, status, due_at);

CREATE INDEX IF NOT EXISTS idx_ops_tasks_owner_due
    ON ops_tasks(owner_name, due_at);

CREATE INDEX IF NOT EXISTS idx_ops_tasks_status_due
    ON ops_tasks(status, due_at);
