-- Smart Solution Telegram group Q&A loop.
-- Pending questions let Michael answer by Telegram reply; answers become semantic memory.

CREATE TABLE IF NOT EXISTS ops_group_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    telegram_message_id INTEGER NOT NULL,
    asker_telegram_user_id BIGINT,
    asker_username VARCHAR(160),
    asker_display_name VARCHAR(240),
    question_text TEXT NOT NULL,
    status VARCHAR(60) NOT NULL DEFAULT 'PENDING_HUMAN',
    answer_text TEXT,
    answer_source VARCHAR(240),
    answered_by VARCHAR(240),
    answered_at TIMESTAMPTZ,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_ops_group_questions_message UNIQUE (chat_id, telegram_message_id)
);

CREATE INDEX IF NOT EXISTS idx_ops_group_questions_status_updated
    ON ops_group_questions(status, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_ops_group_questions_chat_status
    ON ops_group_questions(chat_id, status, telegram_message_id);

INSERT INTO semantic_sources (
    source_code,
    source_type,
    title,
    venue_code,
    uri,
    media_asset_code,
    metadata_json
)
VALUES (
    'SMART_SOLUTION_GROUP_MEMORY',
    'GROUP_QA_MEMORY',
    'Smart Solution team group Q&A memory',
    'AERIS',
    'telegram://smart-solution/group-memory',
    NULL,
    '{"domain":"SMART_SOLUTION_OPS","ragScope":"group_qa"}'::jsonb
)
ON CONFLICT (source_code) DO UPDATE SET
    source_type = EXCLUDED.source_type,
    title = EXCLUDED.title,
    venue_code = EXCLUDED.venue_code,
    uri = EXCLUDED.uri,
    media_asset_code = EXCLUDED.media_asset_code,
    active = TRUE,
    metadata_json = EXCLUDED.metadata_json,
    updated_at = CURRENT_TIMESTAMP;
