-- Telegram Stars payments foundation.
-- Stars are for Telegram digital goods/services: currency XTR, empty provider token.

CREATE TABLE IF NOT EXISTS telegram_star_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    telegram_user_id BIGINT,
    user_id BIGINT,
    venue_code VARCHAR(64) NOT NULL DEFAULT 'AERIS',
    status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
    source VARCHAR(40) NOT NULL DEFAULT 'TELEGRAM',
    purpose VARCHAR(80) NOT NULL,
    related_entity_type VARCHAR(80),
    related_entity_id BIGINT,
    title VARCHAR(240) NOT NULL,
    description TEXT,
    payload VARCHAR(240) NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'XTR',
    star_amount BIGINT NOT NULL,
    provider_token VARCHAR(240) NOT NULL DEFAULT '',
    invoice_message_id BIGINT,
    pre_checkout_query_id VARCHAR(240),
    telegram_payment_charge_id VARCHAR(240),
    provider_payment_charge_id VARCHAR(240),
    failure_reason TEXT,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_telegram_star_payments_payload UNIQUE (payload),
    CONSTRAINT chk_telegram_star_payments_currency CHECK (currency = 'XTR'),
    CONSTRAINT chk_telegram_star_payments_amount CHECK (star_amount > 0),
    CONSTRAINT chk_telegram_star_payments_provider_token CHECK (provider_token = '')
);

CREATE INDEX IF NOT EXISTS idx_telegram_star_payments_chat_created
    ON telegram_star_payments(chat_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_telegram_star_payments_related
    ON telegram_star_payments(related_entity_type, related_entity_id);

CREATE INDEX IF NOT EXISTS idx_telegram_star_payments_status_created
    ON telegram_star_payments(status, created_at DESC);
