-- Durable guest preference memory. FSM writes explicit guest-provided preferences here;
-- AI may later use this as retrieval context, but FSM remains the authority.

CREATE TABLE IF NOT EXISTS guest_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    telegram_user_id BIGINT,
    user_id BIGINT,
    venue_code VARCHAR(64) NOT NULL DEFAULT 'AERIS',
    category VARCHAR(60) NOT NULL,
    preference_text TEXT NOT NULL,
    source VARCHAR(40) NOT NULL DEFAULT 'TELEGRAM',
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    confidence NUMERIC(4, 3) NOT NULL DEFAULT 1.000,
    captured_from_state VARCHAR(80),
    correlation_id VARCHAR(160),
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_guest_preferences_confidence CHECK (confidence >= 0 AND confidence <= 1)
);

CREATE INDEX IF NOT EXISTS idx_guest_preferences_chat_created
    ON guest_preferences(chat_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_guest_preferences_chat_status_category
    ON guest_preferences(chat_id, status, category);

CREATE INDEX IF NOT EXISTS idx_guest_preferences_venue_category
    ON guest_preferences(venue_code, category, created_at DESC);
