-- Foundation for guest feedback and quality loop analytics.
-- Feedback is a product scenario, not a fallback.

CREATE TABLE IF NOT EXISTS guest_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    telegram_user_id BIGINT,
    user_id BIGINT,
    venue_code VARCHAR(64) NOT NULL DEFAULT 'AERIS',
    status VARCHAR(40) NOT NULL DEFAULT 'OPEN',
    source VARCHAR(40) NOT NULL DEFAULT 'TELEGRAM',
    feedback_type VARCHAR(40) NOT NULL DEFAULT 'GENERAL',
    sentiment VARCHAR(40) NOT NULL DEFAULT 'NEUTRAL',
    priority VARCHAR(40) NOT NULL DEFAULT 'NORMAL',
    guest_name VARCHAR(160),
    text TEXT NOT NULL,
    previous_state VARCHAR(80),
    correlation_id VARCHAR(160),
    admin_chat_id VARCHAR(80),
    admin_message_id BIGINT,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_guest_feedback_text CHECK (length(trim(text)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_guest_feedback_chat_created
    ON guest_feedback(chat_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_guest_feedback_status_priority
    ON guest_feedback(status, priority, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_guest_feedback_type_created
    ON guest_feedback(feedback_type, created_at DESC);
