-- Concierge/service requests are explicit guest asks routed to the team.
-- They are not automatic operational confirmations.

CREATE TABLE IF NOT EXISTS concierge_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    telegram_user_id BIGINT,
    user_id BIGINT,
    venue_code VARCHAR(64) NOT NULL DEFAULT 'AERIS',
    request_type VARCHAR(60) NOT NULL DEFAULT 'GENERAL',
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING_TEAM',
    source VARCHAR(40) NOT NULL DEFAULT 'TELEGRAM',
    guest_name VARCHAR(160),
    request_text TEXT NOT NULL,
    manager_chat_id VARCHAR(80),
    captured_from_state VARCHAR(80),
    correlation_id VARCHAR(160),
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_concierge_requests_chat_created
    ON concierge_requests(chat_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_concierge_requests_status_created
    ON concierge_requests(status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_concierge_requests_type_created
    ON concierge_requests(request_type, created_at DESC);
