-- Foundation for table reservations.
-- Event bookings stay separate: they describe large/private events, while
-- table reservations describe concrete seating and time windows.

CREATE TABLE IF NOT EXISTS venue_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_code VARCHAR(64) NOT NULL DEFAULT 'AERIS',
    table_code VARCHAR(32) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    zone VARCHAR(40) NOT NULL,
    capacity_min INTEGER NOT NULL DEFAULT 1,
    capacity_max INTEGER NOT NULL,
    combinable_group VARCHAR(64),
    bookable BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    plan_page INTEGER NOT NULL DEFAULT 2,
    plan_ref TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_venue_tables_code UNIQUE (venue_code, table_code),
    CONSTRAINT chk_venue_tables_capacity CHECK (capacity_min > 0 AND capacity_max >= capacity_min)
);

CREATE INDEX IF NOT EXISTS idx_venue_tables_zone_active
    ON venue_tables(venue_code, zone, active, sort_order);

INSERT INTO venue_tables (
    venue_code,
    table_code,
    display_name,
    zone,
    capacity_min,
    capacity_max,
    combinable_group,
    bookable,
    active,
    plan_page,
    plan_ref,
    sort_order
) VALUES
    ('AERIS', '1', 'Table 1', 'MAIN_HALL', 1, 4, NULL, TRUE, TRUE, 2, 'AERIS PLAN, pages 2-3', 1),
    ('AERIS', '2', 'Table 2', 'MAIN_HALL', 1, 5, NULL, TRUE, TRUE, 2, 'AERIS PLAN, pages 2-3', 2),
    ('AERIS', '3', 'Table 3', 'MAIN_HALL', 1, 4, NULL, TRUE, TRUE, 2, 'AERIS PLAN, pages 2-3', 3),
    ('AERIS', '4', 'Table 4', 'MAIN_HALL', 1, 5, NULL, TRUE, TRUE, 2, 'AERIS PLAN, pages 2-3', 4),
    ('AERIS', '5', 'Table 5', 'MAIN_HALL', 1, 4, NULL, TRUE, TRUE, 2, 'AERIS PLAN, pages 2-3', 5),
    ('AERIS', '6', 'Table 6', 'MAIN_HALL', 1, 4, NULL, TRUE, TRUE, 2, 'AERIS PLAN, pages 2-3', 6),
    ('AERIS', '7', 'Table 7', 'WINE_ROOM', 1, 6, 'WINE_ROOM_7_8', TRUE, TRUE, 2, 'Wine room: tables 7/8 combined up to 12 guests', 7),
    ('AERIS', '8', 'Table 8', 'WINE_ROOM', 1, 6, 'WINE_ROOM_7_8', TRUE, TRUE, 2, 'Wine room: tables 7/8 combined up to 12 guests', 8),
    ('AERIS', '9', 'Table 9', 'MAIN_HALL', 1, 4, NULL, TRUE, TRUE, 2, 'AERIS PLAN, pages 2-3', 9),
    ('AERIS', '10', 'Table 10', 'MAIN_HALL', 1, 4, NULL, TRUE, TRUE, 2, 'AERIS PLAN, pages 2-3', 10),
    ('AERIS', '11', 'Table 11', 'MAIN_HALL', 1, 4, NULL, TRUE, TRUE, 2, 'AERIS PLAN, pages 2-3', 11),
    ('AERIS', '12', 'Table 12', 'MAIN_HALL', 1, 4, NULL, TRUE, TRUE, 2, 'AERIS PLAN, pages 2-3', 12),
    ('AERIS', '13', 'VIP 13', 'VIP_ZONE', 1, 4, 'VIP_13_14_15', TRUE, TRUE, 2, 'VIP zone: tables 13/14/15 combined up to 12 guests', 13),
    ('AERIS', '14', 'VIP 14', 'VIP_ZONE', 1, 4, 'VIP_13_14_15', TRUE, TRUE, 2, 'VIP zone: tables 13/14/15 combined up to 12 guests', 14),
    ('AERIS', '15', 'VIP 15', 'VIP_ZONE', 1, 4, 'VIP_13_14_15', TRUE, TRUE, 2, 'VIP zone: tables 13/14/15 combined up to 12 guests', 15),
    ('AERIS', '16', 'Table 16', 'MAIN_HALL', 1, 4, NULL, TRUE, TRUE, 2, 'AERIS PLAN, pages 2-3', 16),
    ('AERIS', '17', 'Table 17', 'MAIN_HALL', 1, 2, NULL, TRUE, TRUE, 2, 'AERIS PLAN, pages 2-3', 17),
    ('AERIS', '18', 'Table 18', 'MAIN_HALL', 1, 2, NULL, TRUE, TRUE, 2, 'AERIS PLAN, pages 2-3', 18),
    ('AERIS', '19', 'Table 19', 'MAIN_HALL', 1, 2, NULL, TRUE, TRUE, 2, 'AERIS PLAN, pages 2-3', 19),
    ('AERIS', 'BAR', 'Bar seating', 'BAR', 1, 18, 'BAR_COUNTER', TRUE, TRUE, 2, 'Bar zone up to 18 guests', 20)
ON CONFLICT (venue_code, table_code) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    zone = EXCLUDED.zone,
    capacity_min = EXCLUDED.capacity_min,
    capacity_max = EXCLUDED.capacity_max,
    combinable_group = EXCLUDED.combinable_group,
    bookable = EXCLUDED.bookable,
    active = EXCLUDED.active,
    plan_page = EXCLUDED.plan_page,
    plan_ref = EXCLUDED.plan_ref,
    sort_order = EXCLUDED.sort_order,
    updated_at = CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS table_reservation_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    telegram_user_id BIGINT,
    user_id BIGINT,
    table_id BIGINT,
    status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
    source VARCHAR(40) NOT NULL DEFAULT 'TELEGRAM',
    requested_start_at TIMESTAMPTZ,
    requested_end_at TIMESTAMPTZ,
    party_size INTEGER,
    guest_name VARCHAR(160),
    guest_phone VARCHAR(80),
    guest_comment TEXT,
    manager_telegram_id BIGINT NOT NULL DEFAULT 876857557,
    manager_user_id BIGINT,
    hostess_chat_id VARCHAR(120),
    sbis_external_id VARCHAR(120),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_table_reservation_party_size CHECK (party_size IS NULL OR party_size > 0),
    CONSTRAINT chk_table_reservation_window CHECK (
        requested_start_at IS NULL
        OR requested_end_at IS NULL
        OR requested_end_at > requested_start_at
    ),
    CONSTRAINT fk_table_reservation_orders_table
        FOREIGN KEY (table_id) REFERENCES venue_tables(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_table_reservation_orders_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_table_reservation_orders_manager_user
        FOREIGN KEY (manager_user_id) REFERENCES users(id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_table_reservation_orders_chat_created
    ON table_reservation_orders(chat_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_table_reservation_orders_status_time
    ON table_reservation_orders(status, requested_start_at);

CREATE INDEX IF NOT EXISTS idx_table_reservation_orders_table_time
    ON table_reservation_orders(table_id, requested_start_at, requested_end_at)
    WHERE table_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS table_reservation_holds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'HELD',
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_table_reservation_holds_window CHECK (end_at > start_at),
    CONSTRAINT fk_table_reservation_holds_table
        FOREIGN KEY (table_id) REFERENCES venue_tables(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_table_reservation_holds_order
        FOREIGN KEY (order_id) REFERENCES table_reservation_orders(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_table_reservation_holds_table_window
    ON table_reservation_holds(table_id, start_at, end_at, status);

CREATE INDEX IF NOT EXISTS idx_table_reservation_holds_order
    ON table_reservation_holds(order_id);
