-- Foundation for direct staff gratitude / tips.
-- Astor Butler does not collect commission here: it stores intent/order data and
-- prepares a direct SBP boundary between guest and staff or venue.

CREATE TABLE IF NOT EXISTS staff_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_code VARCHAR(64) NOT NULL DEFAULT 'AERIS',
    display_name VARCHAR(160) NOT NULL,
    role VARCHAR(80) NOT NULL,
    telegram_user_id BIGINT,
    phone VARCHAR(80),
    sbp_link TEXT,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_staff_profiles_venue_telegram
    ON staff_profiles(venue_code, telegram_user_id)
    WHERE telegram_user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_staff_profiles_venue_active
    ON staff_profiles(venue_code, active, display_name);

CREATE TABLE IF NOT EXISTS tip_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    telegram_user_id BIGINT,
    user_id BIGINT,
    venue_code VARCHAR(64) NOT NULL DEFAULT 'AERIS',
    staff_id BIGINT REFERENCES staff_profiles(id) ON DELETE SET NULL,
    staff_display_name VARCHAR(160),
    status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
    source VARCHAR(40) NOT NULL DEFAULT 'TELEGRAM',
    amount_minor BIGINT,
    currency VARCHAR(8) NOT NULL DEFAULT 'RUB',
    guest_name VARCHAR(160),
    guest_comment TEXT,
    sbp_url TEXT,
    payment_external_id VARCHAR(160),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_tip_orders_amount CHECK (amount_minor IS NULL OR amount_minor > 0)
);

CREATE INDEX IF NOT EXISTS idx_tip_orders_chat_created
    ON tip_orders(chat_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_tip_orders_status_created
    ON tip_orders(status, created_at DESC);

INSERT INTO staff_profiles (
    venue_code,
    display_name,
    role,
    telegram_user_id,
    metadata_json
) VALUES
    ('AERIS', 'Команда AERIS', 'VENUE_TEAM', 876857557, '{"default":true,"note":"temporary venue/team tip target"}'::jsonb)
ON CONFLICT (venue_code, telegram_user_id) WHERE telegram_user_id IS NOT NULL DO UPDATE SET
    display_name = EXCLUDED.display_name,
    role = EXCLUDED.role,
    active = TRUE,
    metadata_json = EXCLUDED.metadata_json,
    updated_at = CURRENT_TIMESTAMP;
