-- Foundation for merch catalog and guest merch order drafts.
-- Team confirms availability/price before any payment boundary.

CREATE TABLE IF NOT EXISTS merch_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_code VARCHAR(64) NOT NULL DEFAULT 'AERIS',
    item_code VARCHAR(120) NOT NULL,
    title VARCHAR(240) NOT NULL,
    description TEXT,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    price_minor BIGINT,
    currency VARCHAR(8) NOT NULL DEFAULT 'RUB',
    stock_hint VARCHAR(80),
    media_asset_code VARCHAR(120) REFERENCES media_assets(asset_code) ON DELETE SET NULL,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_merch_items_code UNIQUE (venue_code, item_code),
    CONSTRAINT chk_merch_items_price CHECK (price_minor IS NULL OR price_minor > 0)
);

CREATE INDEX IF NOT EXISTS idx_merch_items_venue_status
    ON merch_items(venue_code, status, title);

CREATE TABLE IF NOT EXISTS merch_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT NOT NULL,
    telegram_user_id BIGINT,
    user_id BIGINT,
    venue_code VARCHAR(64) NOT NULL DEFAULT 'AERIS',
    item_id BIGINT REFERENCES merch_items(id) ON DELETE SET NULL,
    item_title VARCHAR(240),
    status VARCHAR(40) NOT NULL DEFAULT 'PENDING_TEAM',
    source VARCHAR(40) NOT NULL DEFAULT 'TELEGRAM',
    quantity INTEGER NOT NULL DEFAULT 1,
    price_minor BIGINT,
    currency VARCHAR(8) NOT NULL DEFAULT 'RUB',
    guest_name VARCHAR(160),
    guest_comment TEXT,
    payment_method_hint VARCHAR(40),
    payment_external_id VARCHAR(160),
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_merch_orders_quantity CHECK (quantity > 0),
    CONSTRAINT chk_merch_orders_price CHECK (price_minor IS NULL OR price_minor > 0)
);

CREATE INDEX IF NOT EXISTS idx_merch_orders_chat_created
    ON merch_orders(chat_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_merch_orders_status_created
    ON merch_orders(status, created_at DESC);

INSERT INTO merch_items (
    venue_code,
    item_code,
    title,
    description,
    status,
    price_minor,
    currency,
    stock_hint,
    metadata_json
) VALUES (
    'AERIS',
    'AERIS_SABRAGE_CHAIN',
    'Сабражная цепь AERIS',
    'Связанный merch item для Safe Play: сувенирная сабражная цепь, наличие и цену подтверждает команда.',
    'ACTIVE',
    NULL,
    'RUB',
    'TEAM_CONFIRMATION_REQUIRED',
    '{"default":true,"safePlayBridge":true}'::jsonb
)
ON CONFLICT (venue_code, item_code) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    stock_hint = EXCLUDED.stock_hint,
    metadata_json = EXCLUDED.metadata_json,
    updated_at = CURRENT_TIMESTAMP;
