-- Foundation for Art Auction / event lot bids.
-- FSM creates bid drafts; final winner/payment is manager/event controlled.

CREATE TABLE IF NOT EXISTS art_auction_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_code VARCHAR(64) NOT NULL DEFAULT 'AERIS',
    event_code VARCHAR(120) NOT NULL,
    title VARCHAR(240) NOT NULL,
    description TEXT,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    donation_initiative_id BIGINT REFERENCES donation_initiatives(id) ON DELETE SET NULL,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_art_auction_events_code UNIQUE (venue_code, event_code)
);

CREATE INDEX IF NOT EXISTS idx_art_auction_events_venue_status
    ON art_auction_events(venue_code, status, starts_at, ends_at);

CREATE TABLE IF NOT EXISTS art_auction_lots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auction_event_id BIGINT NOT NULL REFERENCES art_auction_events(id) ON DELETE CASCADE,
    lot_code VARCHAR(120) NOT NULL,
    title VARCHAR(240) NOT NULL,
    artist_name VARCHAR(200),
    description TEXT,
    status VARCHAR(40) NOT NULL DEFAULT 'ACTIVE',
    starting_price_minor BIGINT,
    min_step_minor BIGINT,
    currency VARCHAR(8) NOT NULL DEFAULT 'RUB',
    media_asset_code VARCHAR(120) REFERENCES media_assets(asset_code) ON DELETE SET NULL,
    metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_art_auction_lots_code UNIQUE (auction_event_id, lot_code),
    CONSTRAINT chk_art_auction_lots_starting_price CHECK (starting_price_minor IS NULL OR starting_price_minor > 0),
    CONSTRAINT chk_art_auction_lots_min_step CHECK (min_step_minor IS NULL OR min_step_minor > 0)
);

CREATE INDEX IF NOT EXISTS idx_art_auction_lots_event_status
    ON art_auction_lots(auction_event_id, status, title);

CREATE TABLE IF NOT EXISTS art_auction_bids (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id BIGINT NOT NULL REFERENCES art_auction_lots(id) ON DELETE RESTRICT,
    chat_id BIGINT NOT NULL,
    telegram_user_id BIGINT,
    user_id BIGINT,
    status VARCHAR(40) NOT NULL DEFAULT 'DRAFT',
    source VARCHAR(40) NOT NULL DEFAULT 'TELEGRAM',
    amount_minor BIGINT NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'RUB',
    bidder_name VARCHAR(160),
    guest_comment TEXT,
    payment_external_id VARCHAR(160),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_art_auction_bids_amount CHECK (amount_minor > 0)
);

CREATE INDEX IF NOT EXISTS idx_art_auction_bids_lot_amount
    ON art_auction_bids(lot_id, amount_minor DESC, created_at);

CREATE INDEX IF NOT EXISTS idx_art_auction_bids_chat_created
    ON art_auction_bids(chat_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_art_auction_bids_status_created
    ON art_auction_bids(status, created_at DESC);

INSERT INTO art_auction_events (
    venue_code,
    event_code,
    title,
    description,
    status,
    metadata_json
) VALUES (
    'AERIS',
    'AERIS_ART_AUCTION_DEFAULT',
    'AERIS Art Auction / тестовый аукцион',
    'Временный активный аукцион до загрузки реальных event/lot материалов.',
    'ACTIVE',
    '{"default":true,"mvp":true}'::jsonb
)
ON CONFLICT (venue_code, event_code) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    metadata_json = EXCLUDED.metadata_json,
    updated_at = CURRENT_TIMESTAMP;

INSERT INTO art_auction_lots (
    auction_event_id,
    lot_code,
    title,
    artist_name,
    description,
    status,
    starting_price_minor,
    min_step_minor,
    currency,
    metadata_json
)
SELECT
    e.id,
    'AERIS_ART_LOT_DEFAULT',
    'AERIS art lot / тестовая работа',
    'AERIS guest artist',
    'Тестовый лот для проверки FSM: реальная картина, файлы и условия будут загружены отдельно.',
    'ACTIVE',
    1000000,
    100000,
    'RUB',
    '{"default":true,"mvp":true}'::jsonb
FROM art_auction_events e
WHERE e.venue_code = 'AERIS'
  AND e.event_code = 'AERIS_ART_AUCTION_DEFAULT'
ON CONFLICT (auction_event_id, lot_code) DO UPDATE SET
    title = EXCLUDED.title,
    artist_name = EXCLUDED.artist_name,
    description = EXCLUDED.description,
    status = EXCLUDED.status,
    starting_price_minor = EXCLUDED.starting_price_minor,
    min_step_minor = EXCLUDED.min_step_minor,
    currency = EXCLUDED.currency,
    metadata_json = EXCLUDED.metadata_json,
    updated_at = CURRENT_TIMESTAMP;
